title: Jaxon
author:
  name: Thierry Feuzeu
  email: 'thierry.feuzeu@lagdo-software.net'
metadata:
    description: 'Jaxon is an open source PHP class library for easily creating Ajax web applications.'
